/**
 * Shared data constants used across Registration, Vendor Dashboard, and Admin Panel.
 * Single source of truth — update here and all 3 areas stay in sync.
 */

// ═══════════════════════════════════════════════════════════
// COUNTRIES — Saudi first, Gulf, Arab, Islamic/Asian, Western, African (no Israel)
// ═══════════════════════════════════════════════════════════
export const COUNTRIES = [
  { code: 'SA', flag: '🇸🇦', nameAr: 'سعودي', nameEn: 'Saudi' },
  { code: 'YE', flag: '🇾🇪', nameAr: 'يمني', nameEn: 'Yemeni' },
  { code: 'EG', flag: '🇪🇬', nameAr: 'مصري', nameEn: 'Egyptian' },
  { code: 'SY', flag: '🇸🇾', nameAr: 'سوري', nameEn: 'Syrian' },
  { code: 'JO', flag: '🇯🇴', nameAr: 'أردني', nameEn: 'Jordanian' },
  { code: 'SD', flag: '🇸🇩', nameAr: 'سوداني', nameEn: 'Sudanese' },
  { code: 'AE', flag: '🇦🇪', nameAr: 'إماراتي', nameEn: 'Emirati' },
  { code: 'KW', flag: '🇰🇼', nameAr: 'كويتي', nameEn: 'Kuwaiti' },
  { code: 'QA', flag: '🇶🇦', nameAr: 'قطري', nameEn: 'Qatari' },
  { code: 'BH', flag: '🇧🇭', nameAr: 'بحريني', nameEn: 'Bahraini' },
  { code: 'OM', flag: '🇴🇲', nameAr: 'عماني', nameEn: 'Omani' },
  { code: 'LB', flag: '🇱🇧', nameAr: 'لبناني', nameEn: 'Lebanese' },
  { code: 'IQ', flag: '🇮🇶', nameAr: 'عراقي', nameEn: 'Iraqi' },
  { code: 'PS', flag: '🇵🇸', nameAr: 'فلسطيني', nameEn: 'Palestinian' },
  { code: 'LY', flag: '🇱🇾', nameAr: 'ليبي', nameEn: 'Libyan' },
  { code: 'TN', flag: '🇹🇳', nameAr: 'تونسي', nameEn: 'Tunisian' },
  { code: 'DZ', flag: '🇩🇿', nameAr: 'جزائري', nameEn: 'Algerian' },
  { code: 'MA', flag: '🇲🇦', nameAr: 'مغربي', nameEn: 'Moroccan' },
  { code: 'MR', flag: '🇲🇷', nameAr: 'موريتاني', nameEn: 'Mauritanian' },
  { code: 'SO', flag: '🇸🇴', nameAr: 'صومالي', nameEn: 'Somali' },
  { code: 'DJ', flag: '🇩🇯', nameAr: 'جيبوتي', nameEn: 'Djiboutian' },
  { code: 'KM', flag: '🇰🇲', nameAr: 'قمري', nameEn: 'Comoran' },
  { code: 'TR', flag: '🇹🇷', nameAr: 'تركي', nameEn: 'Turkish' },
  { code: 'IR', flag: '🇮🇷', nameAr: 'إيراني', nameEn: 'Iranian' },
  { code: 'PK', flag: '🇵🇰', nameAr: 'باكستاني', nameEn: 'Pakistani' },
  { code: 'AF', flag: '🇦🇫', nameAr: 'أفغاني', nameEn: 'Afghan' },
  { code: 'IN', flag: '🇮🇳', nameAr: 'هندي', nameEn: 'Indian' },
  { code: 'BD', flag: '🇧🇩', nameAr: 'بنغلاديشي', nameEn: 'Bangladeshi' },
  { code: 'LK', flag: '🇱🇰', nameAr: 'سريلانكي', nameEn: 'Sri Lankan' },
  { code: 'NP', flag: '🇳🇵', nameAr: 'نيبالي', nameEn: 'Nepali' },
  { code: 'MM', flag: '🇲🇲', nameAr: 'ميانماري', nameEn: 'Burmese' },
  { code: 'TH', flag: '🇹🇭', nameAr: 'تايلاندي', nameEn: 'Thai' },
  { code: 'VN', flag: '🇻🇳', nameAr: 'فيتنامي', nameEn: 'Vietnamese' },
  { code: 'PH', flag: '🇵🇭', nameAr: 'فلبيني', nameEn: 'Filipino' },
  { code: 'ID', flag: '🇮🇩', nameAr: 'إندونيسي', nameEn: 'Indonesian' },
  { code: 'MY', flag: '🇲🇾', nameAr: 'ماليزي', nameEn: 'Malaysian' },
  { code: 'SG', flag: '🇸🇬', nameAr: 'سنغافوري', nameEn: 'Singaporean' },
  { code: 'CN', flag: '🇨🇳', nameAr: 'صيني', nameEn: 'Chinese' },
  { code: 'JP', flag: '🇯🇵', nameAr: 'ياباني', nameEn: 'Japanese' },
  { code: 'KR', flag: '🇰🇷', nameAr: 'كوري', nameEn: 'Korean' },
  { code: 'GB', flag: '🇬🇧', nameAr: 'بريطاني', nameEn: 'British' },
  { code: 'US', flag: '🇺🇸', nameAr: 'أمريكي', nameEn: 'American' },
  { code: 'CA', flag: '🇨🇦', nameAr: 'كندي', nameEn: 'Canadian' },
  { code: 'FR', flag: '🇫🇷', nameAr: 'فرنسي', nameEn: 'French' },
  { code: 'DE', flag: '🇩🇪', nameAr: 'ألماني', nameEn: 'German' },
  { code: 'IT', flag: '🇮🇹', nameAr: 'إيطالي', nameEn: 'Italian' },
  { code: 'ES', flag: '🇪🇸', nameAr: 'إسباني', nameEn: 'Spanish' },
  { code: 'PT', flag: '🇵🇹', nameAr: 'برتغالي', nameEn: 'Portuguese' },
  { code: 'NL', flag: '🇳🇱', nameAr: 'هولندي', nameEn: 'Dutch' },
  { code: 'BE', flag: '🇧🇪', nameAr: 'بلجيكي', nameEn: 'Belgian' },
  { code: 'CH', flag: '🇨🇭', nameAr: 'سويسري', nameEn: 'Swiss' },
  { code: 'AT', flag: '🇦🇹', nameAr: 'نمساوي', nameEn: 'Austrian' },
  { code: 'SE', flag: '🇸🇪', nameAr: 'سويدي', nameEn: 'Swedish' },
  { code: 'NO', flag: '🇳🇴', nameAr: 'نرويجي', nameEn: 'Norwegian' },
  { code: 'DK', flag: '🇩🇰', nameAr: 'دنماركي', nameEn: 'Danish' },
  { code: 'FI', flag: '🇫🇮', nameAr: 'فنلندي', nameEn: 'Finnish' },
  { code: 'PL', flag: '🇵🇱', nameAr: 'بولندي', nameEn: 'Polish' },
  { code: 'GR', flag: '🇬🇷', nameAr: 'يوناني', nameEn: 'Greek' },
  { code: 'RU', flag: '🇷🇺', nameAr: 'روسي', nameEn: 'Russian' },
  { code: 'UA', flag: '🇺🇦', nameAr: 'أوكراني', nameEn: 'Ukrainian' },
  { code: 'RO', flag: '🇷🇴', nameAr: 'روماني', nameEn: 'Romanian' },
  { code: 'AU', flag: '🇦🇺', nameAr: 'أسترالي', nameEn: 'Australian' },
  { code: 'NZ', flag: '🇳🇿', nameAr: 'نيوزيلندي', nameEn: 'New Zealander' },
  { code: 'BR', flag: '🇧🇷', nameAr: 'برازيلي', nameEn: 'Brazilian' },
  { code: 'AR', flag: '🇦🇷', nameAr: 'أرجنتيني', nameEn: 'Argentine' },
  { code: 'MX', flag: '🇲🇽', nameAr: 'مكسيكي', nameEn: 'Mexican' },
  { code: 'CO', flag: '🇨🇴', nameAr: 'كولومبي', nameEn: 'Colombian' },
  { code: 'CL', flag: '🇨🇱', nameAr: 'تشيلي', nameEn: 'Chilean' },
  { code: 'ZA', flag: '🇿🇦', nameAr: 'جنوب أفريقي', nameEn: 'South African' },
  { code: 'NG', flag: '🇳🇬', nameAr: 'نيجيري', nameEn: 'Nigerian' },
  { code: 'KE', flag: '🇰🇪', nameAr: 'كيني', nameEn: 'Kenyan' },
  { code: 'ET', flag: '🇪🇹', nameAr: 'إثيوبي', nameEn: 'Ethiopian' },
  { code: 'GH', flag: '🇬🇭', nameAr: 'غاني', nameEn: 'Ghanaian' },
  { code: 'TZ', flag: '🇹🇿', nameAr: 'تنزاني', nameEn: 'Tanzanian' },
  { code: 'UG', flag: '🇺🇬', nameAr: 'أوغندي', nameEn: 'Ugandan' },
  { code: 'RW', flag: '🇷🇼', nameAr: 'رواندي', nameEn: 'Rwandan' },
  { code: 'MG', flag: '🇲🇬', nameAr: 'مدغشقري', nameEn: 'Malagasy' },
];

// ═══════════════════════════════════════════════════════════
// COUNTRY CODES — for phone number selection
// ═══════════════════════════════════════════════════════════
export const COUNTRY_CODES = [
  // ── GCC + Levant + North Africa (priority — most vendors) ──
  { code: '+966', flag: '🇸🇦', nameAr: 'السعودية' },
  { code: '+971', flag: '🇦🇪', nameAr: 'الإمارات' },
  { code: '+965', flag: '🇰🇼', nameAr: 'الكويت' },
  { code: '+974', flag: '🇶🇦', nameAr: 'قطر' },
  { code: '+973', flag: '🇧🇭', nameAr: 'البحرين' },
  { code: '+968', flag: '🇴🇲', nameAr: 'عُمان' },
  { code: '+20',  flag: '🇪🇬', nameAr: 'مصر' },
  { code: '+962', flag: '🇯🇴', nameAr: 'الأردن' },
  { code: '+961', flag: '🇱🇧', nameAr: 'لبنان' },
  { code: '+964', flag: '🇮🇶', nameAr: 'العراق' },
  { code: '+963', flag: '🇸🇾', nameAr: 'سوريا' },
  { code: '+970', flag: '🇵🇸', nameAr: 'فلسطين' },
  { code: '+967', flag: '🇾🇪', nameAr: 'اليمن' },
  { code: '+249', flag: '🇸🇩', nameAr: 'السودان' },
  { code: '+218', flag: '🇱🇾', nameAr: 'ليبيا' },
  { code: '+216', flag: '🇹🇳', nameAr: 'تونس' },
  { code: '+213', flag: '🇩🇿', nameAr: 'الجزائر' },
  { code: '+212', flag: '🇲🇦', nameAr: 'المغرب' },
  { code: '+222', flag: '🇲🇷', nameAr: 'موريتانيا' },
  { code: '+252', flag: '🇸🇴', nameAr: 'الصومال' },
  { code: '+253', flag: '🇩🇯', nameAr: 'جيبوتي' },
  { code: '+269', flag: '🇰🇲', nameAr: 'جزر القمر' },

  // ── Asia ──
  { code: '+90',  flag: '🇹🇷', nameAr: 'تركيا' },
  { code: '+98',  flag: '🇮🇷', nameAr: 'إيران' },
  { code: '+92',  flag: '🇵🇰', nameAr: 'باكستان' },
  { code: '+91',  flag: '🇮🇳', nameAr: 'الهند' },
  { code: '+880', flag: '🇧🇩', nameAr: 'بنغلاديش' },
  { code: '+94',  flag: '🇱🇰', nameAr: 'سريلانكا' },
  { code: '+977', flag: '🇳🇵', nameAr: 'نيبال' },
  { code: '+975', flag: '🇧🇹', nameAr: 'بوتان' },
  { code: '+960', flag: '🇲🇻', nameAr: 'المالديف' },
  { code: '+93',  flag: '🇦🇫', nameAr: 'أفغانستان' },
  { code: '+62',  flag: '🇮🇩', nameAr: 'إندونيسيا' },
  { code: '+60',  flag: '🇲🇾', nameAr: 'ماليزيا' },
  { code: '+63',  flag: '🇵🇭', nameAr: 'الفلبين' },
  { code: '+66',  flag: '🇹🇭', nameAr: 'تايلاند' },
  { code: '+84',  flag: '🇻🇳', nameAr: 'فيتنام' },
  { code: '+65',  flag: '🇸🇬', nameAr: 'سنغافورة' },
  { code: '+95',  flag: '🇲🇲', nameAr: 'ميانمار' },
  { code: '+855', flag: '🇰🇭', nameAr: 'كمبوديا' },
  { code: '+856', flag: '🇱🇦', nameAr: 'لاوس' },
  { code: '+673', flag: '🇧🇳', nameAr: 'بروناي' },
  { code: '+670', flag: '🇹🇱', nameAr: 'تيمور الشرقية' },
  { code: '+86',  flag: '🇨🇳', nameAr: 'الصين' },
  { code: '+852', flag: '🇭🇰', nameAr: 'هونغ كونغ' },
  { code: '+853', flag: '🇲🇴', nameAr: 'ماكاو' },
  { code: '+886', flag: '🇹🇼', nameAr: 'تايوان' },
  { code: '+81',  flag: '🇯🇵', nameAr: 'اليابان' },
  { code: '+82',  flag: '🇰🇷', nameAr: 'كوريا الجنوبية' },
  { code: '+850', flag: '🇰🇵', nameAr: 'كوريا الشمالية' },
  { code: '+976', flag: '🇲🇳', nameAr: 'منغوليا' },

  // ── Central Asia + Caucasus ──
  { code: '+7',   flag: '🇷🇺', nameAr: 'روسيا/كازاخستان' },
  { code: '+374', flag: '🇦🇲', nameAr: 'أرمينيا' },
  { code: '+994', flag: '🇦🇿', nameAr: 'أذربيجان' },
  { code: '+995', flag: '🇬🇪', nameAr: 'جورجيا' },
  { code: '+992', flag: '🇹🇯', nameAr: 'طاجيكستان' },
  { code: '+993', flag: '🇹🇲', nameAr: 'تركمانستان' },
  { code: '+996', flag: '🇰🇬', nameAr: 'قيرغيزستان' },
  { code: '+998', flag: '🇺🇿', nameAr: 'أوزبكستان' },

  // ── Europe ──
  { code: '+44',  flag: '🇬🇧', nameAr: 'بريطانيا' },
  { code: '+353', flag: '🇮🇪', nameAr: 'أيرلندا' },
  { code: '+33',  flag: '🇫🇷', nameAr: 'فرنسا' },
  { code: '+49',  flag: '🇩🇪', nameAr: 'ألمانيا' },
  { code: '+39',  flag: '🇮🇹', nameAr: 'إيطاليا' },
  { code: '+34',  flag: '🇪🇸', nameAr: 'إسبانيا' },
  { code: '+351', flag: '🇵🇹', nameAr: 'البرتغال' },
  { code: '+31',  flag: '🇳🇱', nameAr: 'هولندا' },
  { code: '+32',  flag: '🇧🇪', nameAr: 'بلجيكا' },
  { code: '+352', flag: '🇱🇺', nameAr: 'لوكسمبورغ' },
  { code: '+41',  flag: '🇨🇭', nameAr: 'سويسرا' },
  { code: '+43',  flag: '🇦🇹', nameAr: 'النمسا' },
  { code: '+45',  flag: '🇩🇰', nameAr: 'الدنمارك' },
  { code: '+46',  flag: '🇸🇪', nameAr: 'السويد' },
  { code: '+47',  flag: '🇳🇴', nameAr: 'النرويج' },
  { code: '+358', flag: '🇫🇮', nameAr: 'فنلندا' },
  { code: '+354', flag: '🇮🇸', nameAr: 'آيسلندا' },
  { code: '+48',  flag: '🇵🇱', nameAr: 'بولندا' },
  { code: '+420', flag: '🇨🇿', nameAr: 'التشيك' },
  { code: '+421', flag: '🇸🇰', nameAr: 'سلوفاكيا' },
  { code: '+36',  flag: '🇭🇺', nameAr: 'المجر' },
  { code: '+40',  flag: '🇷🇴', nameAr: 'رومانيا' },
  { code: '+359', flag: '🇧🇬', nameAr: 'بلغاريا' },
  { code: '+30',  flag: '🇬🇷', nameAr: 'اليونان' },
  { code: '+357', flag: '🇨🇾', nameAr: 'قبرص' },
  { code: '+356', flag: '🇲🇹', nameAr: 'مالطا' },
  { code: '+385', flag: '🇭🇷', nameAr: 'كرواتيا' },
  { code: '+386', flag: '🇸🇮', nameAr: 'سلوفينيا' },
  { code: '+387', flag: '🇧🇦', nameAr: 'البوسنة والهرسك' },
  { code: '+389', flag: '🇲🇰', nameAr: 'مقدونيا الشمالية' },
  { code: '+381', flag: '🇷🇸', nameAr: 'صربيا' },
  { code: '+382', flag: '🇲🇪', nameAr: 'الجبل الأسود' },
  { code: '+355', flag: '🇦🇱', nameAr: 'ألبانيا' },
  { code: '+383', flag: '🇽🇰', nameAr: 'كوسوفو' },
  { code: '+371', flag: '🇱🇻', nameAr: 'لاتفيا' },
  { code: '+370', flag: '🇱🇹', nameAr: 'ليتوانيا' },
  { code: '+372', flag: '🇪🇪', nameAr: 'إستونيا' },
  { code: '+373', flag: '🇲🇩', nameAr: 'مولدوفا' },
  { code: '+375', flag: '🇧🇾', nameAr: 'بيلاروسيا' },
  { code: '+380', flag: '🇺🇦', nameAr: 'أوكرانيا' },
  { code: '+377', flag: '🇲🇨', nameAr: 'موناكو' },
  { code: '+378', flag: '🇸🇲', nameAr: 'سان مارينو' },
  { code: '+423', flag: '🇱🇮', nameAr: 'ليختنشتاين' },
  { code: '+376', flag: '🇦🇩', nameAr: 'أندورا' },

  // ── Americas ──
  { code: '+1',   flag: '🇺🇸', nameAr: 'الولايات المتحدة/كندا' },
  { code: '+52',  flag: '🇲🇽', nameAr: 'المكسيك' },
  { code: '+501', flag: '🇧🇿', nameAr: 'بليز' },
  { code: '+502', flag: '🇬🇹', nameAr: 'غواتيمالا' },
  { code: '+503', flag: '🇸🇻', nameAr: 'السلفادور' },
  { code: '+504', flag: '🇭🇳', nameAr: 'هندوراس' },
  { code: '+505', flag: '🇳🇮', nameAr: 'نيكاراغوا' },
  { code: '+506', flag: '🇨🇷', nameAr: 'كوستاريكا' },
  { code: '+507', flag: '🇵🇦', nameAr: 'بنما' },
  { code: '+509', flag: '🇭🇹', nameAr: 'هايتي' },
  { code: '+53',  flag: '🇨🇺', nameAr: 'كوبا' },
  { code: '+54',  flag: '🇦🇷', nameAr: 'الأرجنتين' },
  { code: '+55',  flag: '🇧🇷', nameAr: 'البرازيل' },
  { code: '+56',  flag: '🇨🇱', nameAr: 'تشيلي' },
  { code: '+57',  flag: '🇨🇴', nameAr: 'كولومبيا' },
  { code: '+58',  flag: '🇻🇪', nameAr: 'فنزويلا' },
  { code: '+51',  flag: '🇵🇪', nameAr: 'بيرو' },
  { code: '+591', flag: '🇧🇴', nameAr: 'بوليفيا' },
  { code: '+592', flag: '🇬🇾', nameAr: 'غويانا' },
  { code: '+593', flag: '🇪🇨', nameAr: 'الإكوادور' },
  { code: '+595', flag: '🇵🇾', nameAr: 'باراغواي' },
  { code: '+597', flag: '🇸🇷', nameAr: 'سورينام' },
  { code: '+598', flag: '🇺🇾', nameAr: 'أوروغواي' },

  // ── Africa (sub-Saharan) ──
  { code: '+27',  flag: '🇿🇦', nameAr: 'جنوب أفريقيا' },
  { code: '+234', flag: '🇳🇬', nameAr: 'نيجيريا' },
  { code: '+254', flag: '🇰🇪', nameAr: 'كينيا' },
  { code: '+255', flag: '🇹🇿', nameAr: 'تنزانيا' },
  { code: '+256', flag: '🇺🇬', nameAr: 'أوغندا' },
  { code: '+250', flag: '🇷🇼', nameAr: 'رواندا' },
  { code: '+251', flag: '🇪🇹', nameAr: 'إثيوبيا' },
  { code: '+291', flag: '🇪🇷', nameAr: 'إريتريا' },
  { code: '+211', flag: '🇸🇸', nameAr: 'جنوب السودان' },
  { code: '+233', flag: '🇬🇭', nameAr: 'غانا' },
  { code: '+225', flag: '🇨🇮', nameAr: 'ساحل العاج' },
  { code: '+237', flag: '🇨🇲', nameAr: 'الكاميرون' },
  { code: '+220', flag: '🇬🇲', nameAr: 'غامبيا' },
  { code: '+221', flag: '🇸🇳', nameAr: 'السنغال' },
  { code: '+223', flag: '🇲🇱', nameAr: 'مالي' },
  { code: '+224', flag: '🇬🇳', nameAr: 'غينيا' },
  { code: '+226', flag: '🇧🇫', nameAr: 'بوركينا فاسو' },
  { code: '+227', flag: '🇳🇪', nameAr: 'النيجر' },
  { code: '+228', flag: '🇹🇬', nameAr: 'توغو' },
  { code: '+229', flag: '🇧🇯', nameAr: 'بنين' },
  { code: '+230', flag: '🇲🇺', nameAr: 'موريشيوس' },
  { code: '+231', flag: '🇱🇷', nameAr: 'ليبيريا' },
  { code: '+232', flag: '🇸🇱', nameAr: 'سيراليون' },
  { code: '+235', flag: '🇹🇩', nameAr: 'تشاد' },
  { code: '+236', flag: '🇨🇫', nameAr: 'أفريقيا الوسطى' },
  { code: '+238', flag: '🇨🇻', nameAr: 'الرأس الأخضر' },
  { code: '+239', flag: '🇸🇹', nameAr: 'ساو تومي وبرينسيب' },
  { code: '+240', flag: '🇬🇶', nameAr: 'غينيا الاستوائية' },
  { code: '+241', flag: '🇬🇦', nameAr: 'الغابون' },
  { code: '+242', flag: '🇨🇬', nameAr: 'الكونغو' },
  { code: '+243', flag: '🇨🇩', nameAr: 'الكونغو الديمقراطية' },
  { code: '+244', flag: '🇦🇴', nameAr: 'أنغولا' },
  { code: '+245', flag: '🇬🇼', nameAr: 'غينيا بيساو' },
  { code: '+248', flag: '🇸🇨', nameAr: 'سيشل' },
  { code: '+257', flag: '🇧🇮', nameAr: 'بوروندي' },
  { code: '+258', flag: '🇲🇿', nameAr: 'موزمبيق' },
  { code: '+260', flag: '🇿🇲', nameAr: 'زامبيا' },
  { code: '+261', flag: '🇲🇬', nameAr: 'مدغشقر' },
  { code: '+263', flag: '🇿🇼', nameAr: 'زيمبابوي' },
  { code: '+264', flag: '🇳🇦', nameAr: 'ناميبيا' },
  { code: '+265', flag: '🇲🇼', nameAr: 'مالاوي' },
  { code: '+266', flag: '🇱🇸', nameAr: 'ليسوتو' },
  { code: '+267', flag: '🇧🇼', nameAr: 'بوتسوانا' },
  { code: '+268', flag: '🇸🇿', nameAr: 'إسواتيني' },

  // ── Oceania ──
  { code: '+61',  flag: '🇦🇺', nameAr: 'أستراليا' },
  { code: '+64',  flag: '🇳🇿', nameAr: 'نيوزيلندا' },
  { code: '+675', flag: '🇵🇬', nameAr: 'بابوا غينيا الجديدة' },
  { code: '+679', flag: '🇫🇯', nameAr: 'فيجي' },
  { code: '+685', flag: '🇼🇸', nameAr: 'ساموا' },
  { code: '+676', flag: '🇹🇴', nameAr: 'تونغا' },
  { code: '+677', flag: '🇸🇧', nameAr: 'جزر سليمان' },
  { code: '+678', flag: '🇻🇺', nameAr: 'فانواتو' },
  { code: '+674', flag: '🇳🇷', nameAr: 'ناورو' },
  { code: '+680', flag: '🇵🇼', nameAr: 'بالاو' },
  { code: '+686', flag: '🇰🇮', nameAr: 'كيريباتي' },
  { code: '+688', flag: '🇹🇻', nameAr: 'توفالو' },
  { code: '+691', flag: '🇫🇲', nameAr: 'ميكرونيزيا' },
  { code: '+692', flag: '🇲🇭', nameAr: 'جزر مارشال' },
];

// Helper: get nationality names for dropdowns
export const getNationalityItems = () => COUNTRIES.map(c => ({
  value: c.nameAr,
  label: c.nameAr,
  prefix: c.flag,
}));

// Helper: get nationality names as flat array
export const getNationalityNames = () => COUNTRIES.map(c => c.nameAr);

// Helper: get country code items for phone dropdowns
export const getCountryCodeItems = () => COUNTRY_CODES.map(c => ({
  value: c.code,
  label: `${c.code} ${c.nameAr}`,
  prefix: c.flag,
}));
