/**
 * Shared data constants used across Registration, Vendor Dashboard, and Admin Panel.
 * Single source of truth — update here and all 3 areas stay in sync.
 */

// ═══════════════════════════════════════════════════════════
// COUNTRIES — Saudi first, Gulf, Arab, Islamic/Asian, Western, African (no Israel)
// ═══════════════════════════════════════════════════════════
export const COUNTRIES = [
  { code: 'SA', flag: '🇸🇦', nameAr: 'سعودي', nameEn: 'Saudi' },
  { code: 'YE', flag: '🇾🇪', nameAr: 'يمني', nameEn: 'Yemeni' },
  { code: 'EG', flag: '🇪🇬', nameAr: 'مصري', nameEn: 'Egyptian' },
  { code: 'SY', flag: '🇸🇾', nameAr: 'سوري', nameEn: 'Syrian' },
  { code: 'JO', flag: '🇯🇴', nameAr: 'أردني', nameEn: 'Jordanian' },
  { code: 'SD', flag: '🇸🇩', nameAr: 'سوداني', nameEn: 'Sudanese' },
  { code: 'AE', flag: '🇦🇪', nameAr: 'إماراتي', nameEn: 'Emirati' },
  { code: 'KW', flag: '🇰🇼', nameAr: 'كويتي', nameEn: 'Kuwaiti' },
  { code: 'QA', flag: '🇶🇦', nameAr: 'قطري', nameEn: 'Qatari' },
  { code: 'BH', flag: '🇧🇭', nameAr: 'بحريني', nameEn: 'Bahraini' },
  { code: 'OM', flag: '🇴🇲', nameAr: 'عماني', nameEn: 'Omani' },
  { code: 'LB', flag: '🇱🇧', nameAr: 'لبناني', nameEn: 'Lebanese' },
  { code: 'IQ', flag: '🇮🇶', nameAr: 'عراقي', nameEn: 'Iraqi' },
  { code: 'PS', flag: '🇵🇸', nameAr: 'فلسطيني', nameEn: 'Palestinian' },
  { code: 'LY', flag: '🇱🇾', nameAr: 'ليبي', nameEn: 'Libyan' },
  { code: 'TN', flag: '🇹🇳', nameAr: 'تونسي', nameEn: 'Tunisian' },
  { code: 'DZ', flag: '🇩🇿', nameAr: 'جزائري', nameEn: 'Algerian' },
  { code: 'MA', flag: '🇲🇦', nameAr: 'مغربي', nameEn: 'Moroccan' },
  { code: 'MR', flag: '🇲🇷', nameAr: 'موريتاني', nameEn: 'Mauritanian' },
  { code: 'SO', flag: '🇸🇴', nameAr: 'صومالي', nameEn: 'Somali' },
  { code: 'DJ', flag: '🇩🇯', nameAr: 'جيبوتي', nameEn: 'Djiboutian' },
  { code: 'KM', flag: '🇰🇲', nameAr: 'قمري', nameEn: 'Comoran' },
  { code: 'TR', flag: '🇹🇷', nameAr: 'تركي', nameEn: 'Turkish' },
  { code: 'IR', flag: '🇮🇷', nameAr: 'إيراني', nameEn: 'Iranian' },
  { code: 'PK', flag: '🇵🇰', nameAr: 'باكستاني', nameEn: 'Pakistani' },
  { code: 'AF', flag: '🇦🇫', nameAr: 'أفغاني', nameEn: 'Afghan' },
  { code: 'IN', flag: '🇮🇳', nameAr: 'هندي', nameEn: 'Indian' },
  { code: 'BD', flag: '🇧🇩', nameAr: 'بنغلاديشي', nameEn: 'Bangladeshi' },
  { code: 'LK', flag: '🇱🇰', nameAr: 'سريلانكي', nameEn: 'Sri Lankan' },
  { code: 'NP', flag: '🇳🇵', nameAr: 'نيبالي', nameEn: 'Nepali' },
  { code: 'MM', flag: '🇲🇲', nameAr: 'ميانماري', nameEn: 'Burmese' },
  { code: 'TH', flag: '🇹🇭', nameAr: 'تايلاندي', nameEn: 'Thai' },
  { code: 'VN', flag: '🇻🇳', nameAr: 'فيتنامي', nameEn: 'Vietnamese' },
  { code: 'PH', flag: '🇵🇭', nameAr: 'فلبيني', nameEn: 'Filipino' },
  { code: 'ID', flag: '🇮🇩', nameAr: 'إندونيسي', nameEn: 'Indonesian' },
  { code: 'MY', flag: '🇲🇾', nameAr: 'ماليزي', nameEn: 'Malaysian' },
  { code: 'SG', flag: '🇸🇬', nameAr: 'سنغافوري', nameEn: 'Singaporean' },
  { code: 'CN', flag: '🇨🇳', nameAr: 'صيني', nameEn: 'Chinese' },
  { code: 'JP', flag: '🇯🇵', nameAr: 'ياباني', nameEn: 'Japanese' },
  { code: 'KR', flag: '🇰🇷', nameAr: 'كوري', nameEn: 'Korean' },
  { code: 'GB', flag: '🇬🇧', nameAr: 'بريطاني', nameEn: 'British' },
  { code: 'US', flag: '🇺🇸', nameAr: 'أمريكي', nameEn: 'American' },
  { code: 'CA', flag: '🇨🇦', nameAr: 'كندي', nameEn: 'Canadian' },
  { code: 'FR', flag: '🇫🇷', nameAr: 'فرنسي', nameEn: 'French' },
  { code: 'DE', flag: '🇩🇪', nameAr: 'ألماني', nameEn: 'German' },
  { code: 'IT', flag: '🇮🇹', nameAr: 'إيطالي', nameEn: 'Italian' },
  { code: 'ES', flag: '🇪🇸', nameAr: 'إسباني', nameEn: 'Spanish' },
  { code: 'PT', flag: '🇵🇹', nameAr: 'برتغالي', nameEn: 'Portuguese' },
  { code: 'NL', flag: '🇳🇱', nameAr: 'هولندي', nameEn: 'Dutch' },
  { code: 'BE', flag: '🇧🇪', nameAr: 'بلجيكي', nameEn: 'Belgian' },
  { code: 'CH', flag: '🇨🇭', nameAr: 'سويسري', nameEn: 'Swiss' },
  { code: 'AT', flag: '🇦🇹', nameAr: 'نمساوي', nameEn: 'Austrian' },
  { code: 'SE', flag: '🇸🇪', nameAr: 'سويدي', nameEn: 'Swedish' },
  { code: 'NO', flag: '🇳🇴', nameAr: 'نرويجي', nameEn: 'Norwegian' },
  { code: 'DK', flag: '🇩🇰', nameAr: 'دنماركي', nameEn: 'Danish' },
  { code: 'FI', flag: '🇫🇮', nameAr: 'فنلندي', nameEn: 'Finnish' },
  { code: 'PL', flag: '🇵🇱', nameAr: 'بولندي', nameEn: 'Polish' },
  { code: 'GR', flag: '🇬🇷', nameAr: 'يوناني', nameEn: 'Greek' },
  { code: 'RU', flag: '🇷🇺', nameAr: 'روسي', nameEn: 'Russian' },
  { code: 'UA', flag: '🇺🇦', nameAr: 'أوكراني', nameEn: 'Ukrainian' },
  { code: 'RO', flag: '🇷🇴', nameAr: 'روماني', nameEn: 'Romanian' },
  { code: 'AU', flag: '🇦🇺', nameAr: 'أسترالي', nameEn: 'Australian' },
  { code: 'NZ', flag: '🇳🇿', nameAr: 'نيوزيلندي', nameEn: 'New Zealander' },
  { code: 'BR', flag: '🇧🇷', nameAr: 'برازيلي', nameEn: 'Brazilian' },
  { code: 'AR', flag: '🇦🇷', nameAr: 'أرجنتيني', nameEn: 'Argentine' },
  { code: 'MX', flag: '🇲🇽', nameAr: 'مكسيكي', nameEn: 'Mexican' },
  { code: 'CO', flag: '🇨🇴', nameAr: 'كولومبي', nameEn: 'Colombian' },
  { code: 'CL', flag: '🇨🇱', nameAr: 'تشيلي', nameEn: 'Chilean' },
  { code: 'ZA', flag: '🇿🇦', nameAr: 'جنوب أفريقي', nameEn: 'South African' },
  { code: 'NG', flag: '🇳🇬', nameAr: 'نيجيري', nameEn: 'Nigerian' },
  { code: 'KE', flag: '🇰🇪', nameAr: 'كيني', nameEn: 'Kenyan' },
  { code: 'ET', flag: '🇪🇹', nameAr: 'إثيوبي', nameEn: 'Ethiopian' },
  { code: 'GH', flag: '🇬🇭', nameAr: 'غاني', nameEn: 'Ghanaian' },
  { code: 'TZ', flag: '🇹🇿', nameAr: 'تنزاني', nameEn: 'Tanzanian' },
  { code: 'UG', flag: '🇺🇬', nameAr: 'أوغندي', nameEn: 'Ugandan' },
  { code: 'RW', flag: '🇷🇼', nameAr: 'رواندي', nameEn: 'Rwandan' },
  { code: 'MG', flag: '🇲🇬', nameAr: 'مدغشقري', nameEn: 'Malagasy' },
];

// ═══════════════════════════════════════════════════════════
// COUNTRY CODES — for phone number selection
// ═══════════════════════════════════════════════════════════
export const COUNTRY_CODES = [
  { code: '+966', flag: '🇸🇦', nameAr: 'السعودية' },
  { code: '+971', flag: '🇦🇪', nameAr: 'الإمارات' },
  { code: '+965', flag: '🇰🇼', nameAr: 'الكويت' },
  { code: '+974', flag: '🇶🇦', nameAr: 'قطر' },
  { code: '+973', flag: '🇧🇭', nameAr: 'البحرين' },
  { code: '+968', flag: '🇴🇲', nameAr: 'عُمان' },
  { code: '+20',  flag: '🇪🇬', nameAr: 'مصر' },
  { code: '+962', flag: '🇯🇴', nameAr: 'الأردن' },
  { code: '+961', flag: '🇱🇧', nameAr: 'لبنان' },
  { code: '+964', flag: '🇮🇶', nameAr: 'العراق' },
  { code: '+963', flag: '🇸🇾', nameAr: 'سوريا' },
  { code: '+970', flag: '🇵🇸', nameAr: 'فلسطين' },
  { code: '+967', flag: '🇾🇪', nameAr: 'اليمن' },
  { code: '+249', flag: '🇸🇩', nameAr: 'السودان' },
  { code: '+218', flag: '🇱🇾', nameAr: 'ليبيا' },
  { code: '+216', flag: '🇹🇳', nameAr: 'تونس' },
  { code: '+213', flag: '🇩🇿', nameAr: 'الجزائر' },
  { code: '+212', flag: '🇲🇦', nameAr: 'المغرب' },
  { code: '+222', flag: '🇲🇷', nameAr: 'موريتانيا' },
  { code: '+252', flag: '🇸🇴', nameAr: 'الصومال' },
  { code: '+90',  flag: '🇹🇷', nameAr: 'تركيا' },
  { code: '+98',  flag: '🇮🇷', nameAr: 'إيران' },
  { code: '+92',  flag: '🇵🇰', nameAr: 'باكستان' },
  { code: '+91',  flag: '🇮🇳', nameAr: 'الهند' },
  { code: '+880', flag: '🇧🇩', nameAr: 'بنغلاديش' },
  { code: '+94',  flag: '🇱🇰', nameAr: 'سريلانكا' },
  { code: '+63',  flag: '🇵🇭', nameAr: 'الفلبين' },
  { code: '+62',  flag: '🇮🇩', nameAr: 'إندونيسيا' },
  { code: '+60',  flag: '🇲🇾', nameAr: 'ماليزيا' },
  { code: '+86',  flag: '🇨🇳', nameAr: 'الصين' },
  { code: '+44',  flag: '🇬🇧', nameAr: 'بريطانيا' },
  { code: '+1',   flag: '🇺🇸', nameAr: 'أمريكا' },
  { code: '+33',  flag: '🇫🇷', nameAr: 'فرنسا' },
  { code: '+49',  flag: '🇩🇪', nameAr: 'ألمانيا' },
  { code: '+39',  flag: '🇮🇹', nameAr: 'إيطاليا' },
  { code: '+34',  flag: '🇪🇸', nameAr: 'إسبانيا' },
  { code: '+61',  flag: '🇦🇺', nameAr: 'أستراليا' },
  { code: '+81',  flag: '🇯🇵', nameAr: 'اليابان' },
  { code: '+82',  flag: '🇰🇷', nameAr: 'كوريا' },
  { code: '+55',  flag: '🇧🇷', nameAr: 'البرازيل' },
  { code: '+7',   flag: '🇷🇺', nameAr: 'روسيا' },
  { code: '+27',  flag: '🇿🇦', nameAr: 'جنوب أفريقيا' },
];

// Helper: get nationality names for dropdowns
export const getNationalityItems = () => COUNTRIES.map(c => ({
  value: c.nameAr,
  label: c.nameAr,
  prefix: c.flag,
}));

// Helper: get nationality names as flat array
export const getNationalityNames = () => COUNTRIES.map(c => c.nameAr);

// Helper: get country code items for phone dropdowns
export const getCountryCodeItems = () => COUNTRY_CODES.map(c => ({
  value: c.code,
  label: `${c.code} ${c.nameAr}`,
  prefix: c.flag,
}));
